# Problem 2
# Even Fibonacci numbers

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.



fibonacci <- data.frame('numbers' = c(1, 2))
while(fibonacci[nrow(fibonacci) -1,] + fibonacci[nrow(fibonacci),] <= 4000000){
  fibonacci[nrow(fibonacci) + 1, ] <- fibonacci[nrow(fibonacci) -1,] + fibonacci[nrow(fibonacci),]
}

even_fibonacci <- data.frame('numbers' = c(2))

for(i in 3:nrow(fibonacci)){
  if(fibonacci[i,]%%2==0){
    even_fibonacci[nrow(even_fibonacci)+1,] <- fibonacci[i,]
  }
}

# sum(even_fibonacci$numbers)
# Solution: 4613732

return(cat(sum(even_fibonacci$numbers)))